"""initial schema

Revision ID: 117bfce5549d
Revises: 
Create Date: 2026-06-20 11:13:55.066691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '117bfce5549d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_memory',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('linkedin', 'twitter', 'blog', 'email', 'whatsapp', 'carousel', 'advisor_talking_points')", name='brand_memory_platform_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_memory_embedding', 'brand_memory', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_brand_memory_platform', 'brand_memory', ['platform'], unique=False)
    op.create_index('idx_brand_memory_published_at', 'brand_memory', [sa.literal_column('published_at DESC')], unique=False)
    op.create_table('cost_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', 'date', name='cost_log_agent_date_uq')
    )
    op.create_index('idx_cost_log_date', 'cost_log', [sa.literal_column('date DESC')], unique=False)
    op.create_table('curated_sites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('section_url', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pre_score_threshold', sa.Float(), server_default=sa.text('4.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_url')
    )
    op.create_table('email_subscribers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('subscribed_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('unsubscribe_token', sa.Text(), server_default=sa.text('gen_random_uuid()::text'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual','website_form')", name='email_subscribers_source_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', 'chunk_index', name='knowledge_base_file_chunk_uq')
    )
    op.create_index('idx_knowledge_base_embedding', 'knowledge_base', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('raw_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('structured_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('word_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pre_score', sa.Float(), nullable=True),
    sa.Column('vision_fallback_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('paywall_detected', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('affected_segments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url')
    )
    op.create_index('idx_raw_content_fetch_date', 'raw_content', [sa.literal_column('fetch_date DESC')], unique=False)
    op.create_index('idx_raw_content_normalized_url', 'raw_content', ['normalized_url'], unique=False)
    op.create_table('run_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('token_cost', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trigger_type IN ('cron','event','manual','orchestrator')", name='run_logs_trigger_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_logs_agent_created', 'run_logs', ['agent_name', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('style_guide',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('linkedin','twitter','blog','email','general')", name='style_guide_platform_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('topic_performance_model',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('topic_category', sa.Text(), nullable=False),
    sa.Column('performance_score', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('sample_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_category')
    )
    op.create_table('user_decision_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('edited_angle', sa.Text(), nullable=True),
    sa.Column('target_persona', sa.Text(), nullable=True),
    sa.Column('source_article_id', sa.UUID(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=False),
    sa.Column('source_article_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.Text(), server_default=sa.text("'pending_approval'"), nullable=False),
    sa.Column('draft_status', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recent_coverage_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('pending_approval','approved','rejected')", name='ideas_approval_status_check'),
    sa.CheckConstraint("platform IN ('linkedin', 'twitter', 'blog', 'email', 'whatsapp', 'carousel', 'advisor_talking_points')", name='ideas_platform_check'),
    sa.ForeignKeyConstraint(['source_article_id'], ['raw_content.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ideas_approval_status', 'ideas', ['approval_status'], unique=False)
    op.create_index('idx_ideas_created_at', 'ideas', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('site_health_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['curated_sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_health_site_created', 'site_health_log', ['site_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('target_persona', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.Text(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=False),
    sa.Column('source_idea_id', sa.UUID(), nullable=True),
    sa.Column('finance_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('suggested_publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.Text(), server_default=sa.text("'pending_approval'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_status IN ('pending_approval','approved','rejected','published','failed')", name='drafts_approval_status_check'),
    sa.CheckConstraint("platform IN ('linkedin', 'twitter', 'blog', 'email', 'whatsapp', 'carousel', 'advisor_talking_points')", name='drafts_platform_check'),
    sa.ForeignKeyConstraint(['source_idea_id'], ['ideas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drafts_due', 'drafts', ['scheduled_at'], unique=False, postgresql_where=sa.text("approval_status = 'approved'"))
    op.create_table('published_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('post_identifier', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_published_posts_draft_id', 'published_posts', ['draft_id'], unique=False)
    op.create_table('content_analytics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('measurement_period', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("measurement_period IN ('24h','72h','7d')", name='content_analytics_period_check'),
    sa.ForeignKeyConstraint(['post_id'], ['published_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'measurement_period', name='content_analytics_post_period_uq')
    )
    op.create_index('idx_content_analytics_post_id', 'content_analytics', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_analytics_post_id', table_name='content_analytics')
    op.drop_table('content_analytics')
    op.drop_index('idx_published_posts_draft_id', table_name='published_posts')
    op.drop_table('published_posts')
    op.drop_index('idx_drafts_due', table_name='drafts', postgresql_where=sa.text("approval_status = 'approved'"))
    op.drop_table('drafts')
    op.drop_index('idx_site_health_site_created', table_name='site_health_log')
    op.drop_table('site_health_log')
    op.drop_index('idx_ideas_created_at', table_name='ideas')
    op.drop_index('idx_ideas_approval_status', table_name='ideas')
    op.drop_table('ideas')
    op.drop_table('user_decision_summaries')
    op.drop_table('topic_performance_model')
    op.drop_table('style_guide')
    op.drop_index('idx_run_logs_agent_created', table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_index('idx_raw_content_normalized_url', table_name='raw_content')
    op.drop_index('idx_raw_content_fetch_date', table_name='raw_content')
    op.drop_table('raw_content')
    op.drop_index('idx_knowledge_base_embedding', table_name='knowledge_base', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_base')
    op.drop_table('email_subscribers')
    op.drop_table('curated_sites')
    op.drop_index('idx_cost_log_date', table_name='cost_log')
    op.drop_table('cost_log')
    op.drop_index('idx_brand_memory_published_at', table_name='brand_memory')
    op.drop_index('idx_brand_memory_platform', table_name='brand_memory')
    op.drop_index('idx_brand_memory_embedding', table_name='brand_memory', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('brand_memory')
    # ### end Alembic commands ###
